module.exports = {
    1: "Uma semente estranha foi plantada nas suas costas ao nascer. A planta brota e cresce com este POKéMON.",
    2: "Quando o bulbo nas suas costas cresce, parece perder a capacidade de ficar de pé sobre suas patas traseiras.",
    3: "A planta floresce quando absorve energia solar. Ela permanece em movimento para procurar luz solar.",
    4: "Obviamente prefere lugares quentes. Quando chove, diz-se que vapor sai da ponta de sua cauda.",
    5: "Quando balança sua cauda ardente, eleva a temperatura a níveis insuportavelmente altos.",
    6: "Cospem fogo quente o suficiente para derreter pedregulhos. Conhecido por causar incêndios florestais involuntariamente.",
    7: "Após o nascimento, suas costas incham e endurecem, formando uma carapaça. Pulveriza poderosamente espuma de sua boca.",
    8: "Frequentemente se esconde na água para caçar presas desavisadas. Para nadar rápido, move as orelhas para manter o equilíbrio.",
    9: "Um POKéMON brutal com jatos de água pressurizada na sua carapaça. Eles são usados para tackles de alta velocidade.",
    10: "Seus pés curtos têm almofadas de sucção que lhe permitem escalar ladeiras e paredes sem parar.",
    11: "Este POKéMON é vulnerável ao ataque enquanto sua carapaça está mole, expondo seu corpo fraco e vulnerável.",
    12: "Em batalha, bate suas asas em alta velocidade para liberar poeira altamente tóxica no ar.",
    13: "Frequentemente encontrado em florestas, comendo folhas. Tem um ferrão venenoso afiado na sua cabeça.",
    14: "Quase incapaz de se mover, este POKéMON só pode endurecer sua carapaça para se proteger dos predadores.",
    15: "Possui três ferrões venenosos nas patas dianteiras e na cauda. Eles são usados para furar o inimigo repetidamente.",
    16: "Uma visão comum em florestas e bosques. Bate suas asas no nível do chão para levantar areia cegante.",
    17: "Muito protetor de sua área territorial, este POKéMON atacará ferozmente qualquer intruso.",
    18: "Ao caçar, raspa a superfície da água em alta velocidade para capturar presas desavisadas, como MAGIKARP.",
    19: "Morde qualquer coisa quando ataca. Pequeno e muito rápido, é uma visão comum em muitos lugares.",
    20: "Usa seus bigodes para manter o equilíbrio. Aparentemente, desacelera se eles forem cortados.",
    21: "Bate suas pequenas asas de forma ocupada para voar. Usando seu bico, procura presas na grama.",
    22: "Com suas enormes e magníficas asas, pode se manter no ar sem precisar pousar para descansar.",
    23: "Move-se silenciosamente e furtivamente. Come os ovos de aves, como PIDGEY e SPEAROW, inteiros.",
    24: "Diz-se que as marcas de advertência ferozes em sua barriga diferem de área para área.",
    25: "Quando vários desses POKéMON se reúnem, sua eletricidade pode se acumular e causar tempestades de raios.",
    26: "Sua cauda longa serve como um aterramento para se proteger de sua própria alta voltagem.",
    27: "Cava profundamente no subsolo em locais áridos, longe da água. Só emerge para caçar alimento.",
    28: "Se encolhe em uma bola espinhosa quando ameaçado. Pode rolar enquanto encolhido para atacar ou escapar.",
    29: "Embora pequeno, seus espinhos venenosos tornam este POKéMON perigoso. A fêmea tem chifres menores.",
    30: "O chifre da fêmea se desenvolve lentamente. Prefere ataques físicos como arranhar e morder.",
    31: "Suas escamas duras oferecem forte proteção. Usa sua grande massa para executar movimentos poderosos.",
    32: "Endurece suas orelhas para sentir o perigo. Quanto maiores seus chifres, mais potente seu veneno secreto.",
    33: "Um POKéMON agressivo que ataca rapidamente. O chifre em sua cabeça secreta um veneno potente.",
    34: "Usa sua poderosa cauda em batalha para esmagar, apertar e quebrar os ossos da presa.",
    35: "Seu apelo mágico e fofo tem muitos admiradores. É raro e encontrado apenas em certas áreas.",
    36: "Um POKéMON tímido e raro que é difícil de ser visto. Vai correr e se esconder assim que perceber a presença de pessoas.",
    37: "Ao nascer, tem apenas uma cauda. A cauda se divide da ponta à medida que envelhece.",
    38: "Muito inteligente e vingativo. Agarrar uma das muitas caudas pode resultar em uma maldição de 1000 anos.",
    39: "Quando seus enormes olhos se iluminam, ele canta uma melodia misteriosamente suave que coloca seus inimigos para dormir.",
    40: "Seu corpo é macio e borrachudo. Quando irritado, ele incha e se infla para um tamanho enorme.",
    41: "Formam colônias em lugares perpetuamente escuros. Usam ondas ultrassônicas para identificar e se aproximar de alvos.",
    42: "Uma vez que ataca, não para de drenar energia da vítima, mesmo se ficar muito pesada para voar.",
    43: "Durante o dia, mantém seu rosto enterrado no chão. À noite, vaga por aí semeando suas sementes.",
    44: "O fluido que sai de sua boca não é baba. É um néctar usado para atrair presas.",
    45: "Possui as pétalas maiores do mundo. A cada passo, as pétalas liberam nuvens pesadas de pólen tóxico.",
    46: "Cava para sugar as raízes das árvores. Os cogumelos em suas costas crescem ao extrair nutrientes do hospedeiro inseto.",
    47: "Uma par de hospedeiro-parasita em que o cogumelo parasita dominou o inseto hospedeiro. Prefere lugares úmidos.",
    48: "Vive nas sombras de árvores altas, onde come insetos. É atraído pela luz à noite.",
    49: "As escamas parecidas com pó que cobrem suas asas são codificadas por cores para indicar os tipos de veneno que possui.",
    50: "Vive cerca de um metro abaixo do solo, onde se alimenta das raízes das plantas. Às vezes aparece acima do solo.",
    51: "Uma equipe de três DIGLETTs. Provoca grandes terremotos ao cavar 60 milhas abaixo da terra.",
    52: "Lava seu rosto regularmente para manter a moeda em sua testa impecável. Não se dá bem com o Meowth Galariano.",
    53: "Embora sua pelagem tenha muitos admiradores, é difícil criá-lo como um animal de estimação devido à sua natureza imprevisível.",
    54: "Enquanto embala seus inimigos com seu olhar vago, este astuto POKéMON usa poderes psicocinéticos.",
    55: "Frequentemente visto nadando elegantemente nas margens de lagos. É frequentemente confundido com o monstro japonês, Kappa.",
    56: "Extremamente rápido para se irritar. Pode ser dócil em um momento e logo depois começar a agitar violentamente.",
    57: "Sempre furioso e tenaz. Não abandonará a perseguição até que sua presa seja pega.",
    58: "Muito protetor de seu território. Ladrará e morderá para repelir intrusos de seu espaço.",
    59: "Um POKéMON admirado desde o passado por sua beleza. Corre agilmente como se estivesse sobre asas.",
    60: "Seus novos membros impedem que ele corra. Parece preferir nadar a tentar ficar de pé.",
    61: "Capaz de viver tanto na água quanto fora dela. Quando fora da água, sua pele exala umidade para se manter escorregadia.",
    62: "Um nadador habilidoso tanto no estilo crawl quanto no peito. Facilmente ultrapassa até os melhores nadadores humanos.",
    63: "Usando sua habilidade de ler mentes, identificará o perigo iminente e usará TELEPORT para se salvar.",
    64: "Emite ondas alfa especiais de seu corpo que causam dores de cabeça apenas por estar perto.",
    65: "Seu cérebro pode superar um supercomputador. Seu QI é dito ser 5.000.",
    66: "Adora desenvolver seus músculos. Treina em todos os estilos de artes marciais para se tornar ainda mais forte.",
    67: "Seu corpo musculoso é tão potente que precisa usar um cinto para economizar energia e regular seus movimentos.",
    68: "Usando seus músculos pesados, dá socos poderosos que podem lançar a vítima para além do horizonte.",
    69: "Um POKéMON carnívoro que captura e come insetos. Usa seus pés raízes para absorver a umidade necessária.",
    70: "Cuspir PÓS Venenosos para imobilizar o inimigo e depois finalizá-lo com um spray de ÁCIDO.",
    71: "Dizem que vive em enormes colônias nas profundezas das selvas, embora ninguém tenha retornado de lá.",
    72: "Flutua em mares rasos. Pescadores que a fisgam acidentalmente geralmente são punidos com seu ácido picante.",
    73: "Os tentáculos geralmente são mantidos curtos. Em caçadas, são usados para pegar a presa sem se revelar.",
    74: "Onde pode ser encontrado o maior número de POKéMON marinhos?",
    75: "Este POKéMON se esconde nas cavernas mais profundas, onde a luz não chega. Sua presença é sinalizada por um som suave.",
  76: "O corpo de STEELIX é feito de aço e minerais. Ele pode viver por séculos, cavando profundamente no solo.",
  77: "Este POKéMON tem uma grande força física. Seus ataques com suas poderosas garras podem destruir rochas com facilidade.",
  78: "Com seu corpo pesado e suas presas afiadas, ele destrói tudo ao seu redor, incluindo árvores e pedras.",
  79: "Sua juba de fogo brilha intensamente durante a batalha. O calor gerado é suficiente para derreter metal.",
  80: "Um POKéMON feroz que só pode ser domado com muito esforço. Ele é conhecido por atacar sem aviso.",
  81: "Envolvendo-se com sua névoa mágica, este POKéMON pode ficar invisível e disparar ataques surpresa.",
  82: "Famoso por seu olhar hipnótico, ele pode colocar qualquer um em um sono profundo com apenas um olhar.",
  83: "Este POKéMON é conhecido por sua habilidade de criar ilusões de maneira excelente, confundindo seus inimigos.",
  84: "Sempre alerta, este POKéMON mantém um território bem definido e pode atacar qualquer intruso com velocidade.",
  85: "A força de suas pernas permite que ele dê saltos incríveis e escape de seus predadores facilmente.",
  86: "Este POKéMON poderoso é conhecido por sua habilidade de atacar com sua cauda afiada, capaz de cortar rochas.",
  87: "Uma criatura enérgica que pode correr a altíssimas velocidades. Sua agilidade a torna muito difícil de pegar.",
  88: "Este POKéMON voa por grandes distâncias. Sua habilidade de controlar os ventos faz dele um mestre das corridas.",
  89: "Uma forma primitiva de POKéMON que ainda mantém muitos traços de seu antigo antepassado.",
  90: "Com suas incríveis habilidades de camuflagem, ele se esconde facilmente no ambiente, tornando-se quase invisível.",
  91: "Muito inteligente, ele usa sua força mental para se proteger. Pode realizar ataques poderosos com sua mente.",
  92: "Possui uma habilidade rara de controlar o clima, o que o torna um adversário formidável em combate.",
  93: "Com suas longas asas, ele pode voar de maneira silenciosa, surpreendendo seus oponentes com ataques rápidos.",
  94: "Possui habilidades psíquicas tão avançadas que pode criar barreiras de proteção contra ataques físicos e especiais.",
  95: "Este POKéMON é conhecido por sua lealdade. Ele ajudará seu treinador em batalha com grande força.",
  96: "Possui grandes habilidades de combate corpo a corpo, usando suas garras afiadas para rasgar qualquer adversário.",
  97: "Com sua habilidade única, ele pode gerar eletricidade a partir de seu corpo, usando-a para atacar com grande potência.",
  98: "Este POKéMON voa em círculos em alta velocidade, criando redemoinhos de vento que podem desorientar seus oponentes.",
  99: "Este POKéMON é misterioso e exibe um comportamento imprevisível. Seus ataques incluem poderosas rajadas de energia.",
  100: "Usa suas poderosas garras e cauda para defender-se de qualquer ameaça, sendo capaz de causar grandes danos.",
  101: "Este POKéMON se adapta bem a qualquer ambiente. Seu corpo é flexível, permitindo-lhe sobreviver até nos locais mais difíceis.",
  102: "A presença deste POKéMON é considerada uma boa sorte. Ele usa seus poderes psíquicos para se comunicar com outros Pokémon.",
  103: "Conhecido por sua grande resistência, ele é capaz de resistir a ataques diretos e reagir com grande força.",
  104: "Este POKéMON é muito curioso. Seu comportamento errático o torna difícil de prever, especialmente durante uma batalha.",
  105: "Seu corpo pode se dividir em várias partes menores, permitindo que ele se multiplique rapidamente para escapar de uma situação perigosa.",
  106: "De aparência ameaçadora, este POKéMON pode atacar com sua enorme força física, deixando uma destruição massiva em seu caminho.",
  107: "Este POKéMON é conhecido por suas habilidades mágicas. Ele pode transformar o ambiente ao seu redor com apenas um movimento.",
  108: "Atinge velocidades incrivelmente altas, podendo escapar de quase qualquer predador. Sua velocidade é sua melhor defesa.",
  109: "Com uma pele extremamente dura e escorregadia, ele pode se proteger de quase qualquer ataque, mantendo-se intacto.",
  110: "Seu comportamento calmo e sereno esconde sua incrível força. Ele pode derrubar adversários com um único golpe.",
  111: "A habilidade de gerar chamas intensas em sua cauda torna este POKéMON um adversário formidável em qualquer batalha.",
  112: "Este POKéMON é uma das criaturas mais poderosas que existe, com a capacidade de controlar as forças naturais da terra.",
  113: "Com sua aparência intimidante, ele usa sua força física para destruir qualquer obstáculo em seu caminho.",
  114: "Sua habilidade de disparar ondas sonoras é uma das mais poderosas entre os POKéMON, capaz de causar danos maciços.",
  115: "Este POKéMON se esconde nas sombras, saindo apenas para atacar sua presa de forma extremamente furtiva.",
  116: "É capaz de alterar o curso de um combate com a velocidade de seus ataques, tornando-o um oponente perigoso.",
  117: "Com sua grande resistência e habilidades de combate, ele pode facilmente dominar a maioria dos oponentes em batalhas.",
  118: "Este POKéMON usa sua cauda para se defender de qualquer ameaça. Ele é muito ágil e sabe como escapar rapidamente.",
  119: "Possui um poder imenso e é capaz de controlar os ventos com facilidade. Ele pode criar tornados com apenas um movimento.",
  120: "Sua habilidade de gerar fogo e calor imensos o torna um adversário imbatível para qualquer Pokémon que não esteja preparado.",
  121: "Com suas longas antenas, ele pode detectar movimentos ao redor com grande precisão, tornando-o um excelente rastreador.",
  122: "Este POKéMON é muito territorial e pode ser extremamente agressivo se alguém invadir seu espaço.",
  123: "Com um corpo flexível e ágil, ele pode se esquivar de ataques e atacar de maneira eficaz com suas garras afiadas.",
  124: "Sua habilidade de manipular o clima lhe dá uma vantagem estratégica em qualquer batalha, criando tempestades intensas.",
  125: "Conhecido por sua velocidade impressionante, ele pode se mover tão rápido que se torna invisível aos olhos dos inimigos.",
  126: "Possui habilidades elétricas incrivelmente poderosas. Seus ataques são capazes de desativar dispositivos e derrotar adversários com um único golpe.",
  127: "Este POKéMON se move através da água com grande facilidade, podendo nadar a grandes velocidades e atacar com força.",
  128: "Com suas garras afiadas e poderosos músculos, ele é um adversário temido por muitos. Ele pode lutar de maneira implacável.",
  129: "Este POKéMON é especialista em camuflagem e pode se esconder facilmente entre as folhas ou pedras para surpreender seus inimigos.",
  130: "Sua habilidade de produzir ondas elétricas a partir de seu corpo o torna um oponente muito difícil de derrotar.",
  131: "Com um corpo composto principalmente por água, ele pode facilmente se misturar aos rios e lagos, tornando-se quase invisível.",
  132: "Muito engenhoso, ele é capaz de criar estratégias rápidas durante a batalha, tornando-se imprevisível e difícil de derrotar.",
  133: "Este POKéMON é conhecido por sua versatilidade, capaz de se adaptar a diversas situações. Ele pode evoluir de várias formas.",
  134: "Com seu corpo elegante e fins aquáticos, ele nada rapidamente através das águas e é muito ágil em batalhas subaquáticas.",
  135: "Este POKéMON possui uma habilidade única de controlar a eletricidade. Seus ataques podem causar sérios danos a qualquer inimigo.",
  136: "Com suas habilidades de voo, ele pode atacar de cima com grande precisão, tornando-o um oponente difícil de combater.",
  137: "Seu canto é tão bonito e poderoso que pode afetar a mente dos oponentes, colocando-os em um estado de transe.",
  138: "Este POKéMON pode se mover em grandes profundidades e sobreviver em ambientes de baixa luminosidade, adaptando-se com facilidade.",
  139: "Com uma combinação de força física e habilidades de voo, ele pode causar danos significativos aos oponentes enquanto se mantém ágil.",
  140: "Este POKéMON é famoso por sua resistência e habilidades de combate. Ele pode resistir a ataques potentes e contra-atacar com força.",
  141: "Com um corpo muito resistente, ele pode se esconder em locais apertados e atacar com força surpresa.",
  142: "Este POKéMON voa com uma velocidade impressionante. Sua agilidade no ar torna-o um excelente atacante à distância.",
  143: "Conhecido por seu apetite insaciável, ele se alimenta de grandes quantidades de comida e pode dormir por longos períodos.",
  144: "Este POKéMON é um mestre dos ventos. Ele pode controlar grandes tempestades e gerar ventanias com um único movimento.",
  145: "Com suas asas imponentes, ele voa por grandes distâncias e é capaz de criar tempestades de areia para desorientar os adversários.",
  146: "Possui um controle impressionante sobre as forças da água, podendo gerar enormes ondas e controlar correntes marinhas.",
  147: "Este POKéMON tem uma aparência feroz, mas seu comportamento é muitas vezes calmo. Ele usa suas habilidades mentais para se proteger.",
  148: "Este POKéMON pode alterar sua forma durante a batalha, mudando seu estilo de ataque conforme necessário.",
  149: "Com sua habilidade de controlar as tempestades, ele é capaz de gerar furacões e raios, sendo um oponente incrivelmente poderoso.",
  150: "Considerado um dos Pokémon mais poderosos, ele é capaz de destruir montanhas com seu poder energético e controlado.",
  151: "Um Pokémon mítico, conhecido por sua habilidade de controlar o tempo e o espaço. Sua presença é rara, mas é um símbolo de grande poder e sabedoria."  
};
  